// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRbxrK7GW9bkoph2wlcT-QXKyeEMiebk8',
    appId: '1:1092034153395:web:4c916a7a904651852899c6',
    messagingSenderId: '1092034153395',
    projectId: 'tastebyyou-36078',
    authDomain: 'tastebyyou-36078.firebaseapp.com',
    databaseURL:
        'https://tastebyyou-36078-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tastebyyou-36078.appspot.com',
    measurementId: 'G-QHR2NB0SGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcSz5KfAmovkfYqQ4mLV4SFyDxY9YpfB4',
    appId: '1:1092034153395:android:4230ed571788a0472899c6',
    messagingSenderId: '1092034153395',
    projectId: 'tastebyyou-36078',
    databaseURL:
        'https://tastebyyou-36078-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tastebyyou-36078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLm27hfs6sGCfkPtYcICGHZQR2rY-5iU',
    appId: '1:1092034153395:ios:942c4e58dea6966d2899c6',
    messagingSenderId: '1092034153395',
    projectId: 'tastebyyou-36078',
    databaseURL:
        'https://tastebyyou-36078-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tastebyyou-36078.appspot.com',
    iosClientId:
        '1092034153395-j1tkttdsp2ia9ks41mplcu07osfm9inn.apps.googleusercontent.com',
    iosBundleId: 'io.sspzoa.tastebyyou',
  );
}
